import streamlit as st

# 支持的语言列表
LANGUAGES = {
    "zh": "中文",
    "en": "English",
    "ja": "日本語",
    "ko": "한국어"
}

# 翻译文本字典
TRANSLATIONS = {
    # 中文
    "zh": {
        "app_title": "二手交易平台",
        "page_titles": {
            "search": "商品搜索",
            "auth": "用户认证",
            "publish": "发布商品",
            "my_products": "我的商品",
            "profile": "用户中心",
            "messages": "消息中心"
        },
        "menu": {
            "title": "导航菜单",
            "search": " 商品搜索",
            "messages": " 消息中心",
            "publish": " 发布商品",
            "my_products": " 我的商品",
            "profile": " 用户中心",
            "auth": " 用户认证"
        },
        "auth": {
            "login": "登录",
            "register": "注册",
            "username": "用户名",
            "email": "邮箱",
            "password": "密码",
            "confirm_password": "确认密码",
            "new_password": "新密码",
            "already_account": "已有账号？",
            "no_account": "还没有账号？",
            "login_success": "登录成功！",
            "register_success": "注册成功！",
            "login_failed": "登录失败，请检查用户名和密码",
            "register_failed": "注册失败，请检查输入信息",
            "logout": "退出登录",
            "login_prompt": "请登录以使用完整功能",
            "please_login": "请先登录",
            "login_button": "登录",
            "register_button": "注册",
            "fill_all_fields": "请填写所有字段",
            "password_mismatch": "两次输入的密码不一致",
            "enter_username_password": "请输入用户名和密码",
            "username_email_exists": "用户名或邮箱已存在",
            "reset_password": "找回密码",
            "send_code": "发送验证码",
            "verification_code": "验证码",
            "reset_password_button": "重置密码",
            "email_not_configured": "邮件服务未配置，无法发送验证码",
            "email_sent": "邮件已发送，请查收验证码",
            "email_send_failed": "邮件发送失败：{}",
            "user_not_found_by_email": "未找到该邮箱对应的用户",
            "code_invalid": "验证码无效",
            "code_expired": "验证码已过期，请重新发送",
            "reset_success": "密码重置成功，请使用新密码登录"
        },
        "search": {
            "search_bar": "搜索商品...",
            "search_button": "搜索",
            "cancel": "取消",
            "filter_category": "商品分类",
            "sort_price": "价格排序",
            "sort_newest": "最新上架",
            "sort_price_low": "价格从低到高",
            "sort_price_high": "价格从高到低",
            "all": "全部",
            "price_range": "价格范围",
            "price_low": "最低价格",
            "price_high": "最高价格",
            "no_results": "没有找到符合条件的商品",
            "view_details": "查看详情",
            "results_found": "找到",
            "products": "个商品",
            "back_to_list": "返回列表"
        },
        "product": {
            "multilingual_description": "多语言描述",
            "optional_description": "可选",
            "at_least_one_description_required": "至少需要提供一种语言的描述",
            "publish_title": "发布新商品",
            "product_name": "商品名称",
            "product_description": "商品描述",
            "product_image": "商品图片",
            "product_price": "商品价格",
            "product_category": "商品分类",
            "product_image": "商品图片",
            "publish_button": "发布商品",
            "update_button": "更新商品",
            "delete_button": "删除商品",
            "confirm_delete": "确定要删除这个商品吗？",
            "published_success": "商品发布成功！",
            "updated_success": "商品更新成功！",
            "deleted_success": "商品删除成功！",
            "seller": "卖家",
            "contact_seller": "联系卖家",
            "image_not_found": "图片未找到或已被删除",
            "cannot_contact_self": "您不能联系自己",
            "login_to_contact": "请先登录后联系卖家",
            "title": "商品标题",
            "description": "商品描述",
            "price": "价格",
            "category": "分类",
            "condition": "新旧程度",
            "contact_info": "联系信息",
            "upload_image": "上传图片",
            "submit": "发布商品",
            "fill_required": "请填写所有必填项",
            "no_products": "您还没有发布任何商品",
            "edit": "编辑",
            "delete": "删除",
            "created_at": "发布时间",
            "info": "商品信息",
            "seller_info_unavailable": "卖家信息不可用",
            "contact": "联系卖家",
            "safe_transaction_message": "为了安全交易，建议通过平台消息系统联系卖家",
            "contact_phone": "联系电话",
            "publish_success": "商品发布成功！",
            "publish_failed": "发布失败",
            "categories": {
                "electronics": "电子产品",
                "household": "家居用品",
                "clothing": "服装",
                "books": "图书",
                "sports": "运动用品",
                "other": "其他"
            },
            "conditions": {
                "new": "全新",
                "like_new": "几乎全新",
                "minor_wear": "轻微使用痕迹",
                "normal": "正常使用",
                "heavy_wear": "使用较久"
            },
            "image_not_found": "图片文件不存在"
        },
        "messages": {
            "messages_center": "消息中心",
            "no_conversations": "您还没有任何对话",
            "start_chat": "与其他用户互动开始聊天吧",
            "start_chat_prompt": "开始与其他用户聊天互动吧",
            "select_contact": "请从左侧选择一个联系人开始聊天",
            "select_contact_first": "请先选择一个联系人开始聊天",
            "start_conversation": "开始对话吧！",
            "type_message": "输入消息...",
            "input_label": "消息",
            "input_placeholder": "输入消息...",
            "send": "发送",
            "send_button": "发送",
            "send_success": "消息发送成功",
            "send_error": "发送消息失败",
            "refresh_messages": "刷新消息",
            "refresh": "刷新消息",
            "refresh_help": "刷新消息列表",
            "sending_message": "正在发送消息...",
            "message_sent_success": "消息发送成功!",
            "message_sent_failed": "消息发送失败",
            "error_sending": "发送消息时出错: {}",
            "cannot_contact_self": "不能联系自己",
            "chat_settings": "聊天设置",
            "chat_settings_help": "聊天相关设置",
            "operation_irreversible": "操作不可逆，请谨慎使用！",
            "clear_chat_history": "清空聊天记录",
            "clear_history_help": "删除与该用户的所有聊天记录（不可逆）",
            "confirm_clear_history": "确认清空所有聊天记录？此操作不可逆！",
            "confirm": "确认清空",
            "cancel": "取消"
        },
        "profile": {
            "username": "用户名",
            "email": "邮箱",
            "login_required": "请先登录"
        },
        "general": {
            "save": "保存",
            "cancel": "取消",
            "confirm": "确认",
            "success": "成功",
            "error": "错误",
            "warning": "警告",
            "info": "提示",
            "settings": "设置",
            "price": "价格",
            "description": "描述",
            "category": "分类",
            "time": "时间",
            "date": "日期"
        }
    },
    # 英文
    "en": {
        "app_title": "Second-hand Trading Platform",
        "page_titles": {
            "search": "Product Search",
            "auth": "User Authentication",
            "publish": "Publish Product",
            "my_products": "My Products",
            "profile": "User Profile",
            "messages": "Message Center"
        },
        "menu": {
            "title": "Navigation Menu",
            "search": "🔍 Search Products",
            "messages": "💬 Messages",
            "publish": "➕ Publish Product",
            "my_products": "📦 My Products",
            "profile": "👤 Profile",
            "auth": "🔐 Authentication"
        },
        "auth": {
            "login": "Login",
            "register": "Register",
            "username": "Username",
            "email": "Email",
            "password": "Password",
            "confirm_password": "Confirm Password",
            "new_password": "New Password",
            "already_account": "Already have an account?",
            "no_account": "Don't have an account?",
            "login_success": "Login successful!",
            "register_success": "Registration successful!",
            "login_failed": "Login failed, please check username and password",
            "register_failed": "Registration failed, please check your input",
            "logout": "Logout",
            "login_prompt": "Please log in to use full features",
            "please_login": "Please log in first",
            "login_button": "Login",
            "register_button": "Register",
            "fill_all_fields": "Please fill in all fields",
            "password_mismatch": "Passwords do not match",
            "enter_username_password": "Please enter username and password",
            "username_email_exists": "Username or email already exists",
            "reset_password": "Reset Password",
            "send_code": "Send Code",
            "verification_code": "Verification Code",
            "reset_password_button": "Reset Password",
            "email_not_configured": "Email service not configured; cannot send code",
            "email_sent": "Email sent; please check your inbox",
            "email_send_failed": "Failed to send email: {}",
            "user_not_found_by_email": "No user found with this email",
            "code_invalid": "Invalid verification code",
            "code_expired": "Verification code expired; please resend",
            "reset_success": "Password reset successful; please log in with the new password"
        },
        "search": {
            "search_bar": "Search products...",
            "search_button": "Search",
            "cancel": "Cancel",
            "filter_category": "Categories",
            "sort_price": "Sort by price",
            "sort_newest": "Newest first",
            "sort_price_low": "Price: Low to High",
            "sort_price_high": "Price: High to Low",
            "all": "All",
            "price_range": "Price range",
            "price_low": "Minimum price",
            "price_high": "Maximum price",
            "no_results": "No products found",
            "view_details": "View details",
            "results_found": "Found",
            "products": "products",
            "back_to_list": "Back to List"
        },
        "product": {
            "multilingual_description": "Multilingual Description",
            "optional_description": "Optional",
            "at_least_one_description_required": "At least one language description is required",
            "publish_title": "Publish New Product",
            "product_name": "Product name",
            "product_description": "Description",
            "multilingual_description": "Multilingual Description",
            "optional_description": "Optional",
            "at_least_one_description_required": "At least one language description is required",
            "product_image": "Product image",
            "product_price": "Price",
            "product_category": "Category",
            "product_image": "Product image",
            "publish_button": "Publish",
            "update_button": "Update",
            "delete_button": "Delete",
            "confirm_delete": "Are you sure you want to delete this product?",
            "published_success": "Product published successfully!",
            "updated_success": "Product updated successfully!",
            "deleted_success": "Product deleted successfully!",
            "seller": "Seller",
            "contact_seller": "Contact seller",
            "cannot_contact_self": "You cannot contact yourself",
            "login_to_contact": "Please login to contact seller",
            "title": "Product Title",
            "description": "Product Description",
            "price": "Price",
            "category": "Category",
            "condition": "Condition",
            "contact_info": "Contact Info",
            "upload_image": "Upload Image",
            "submit": "Publish Product",
            "fill_required": "Please fill in all required fields",
            "no_products": "You haven't published any products yet",
            "edit": "Edit",
            "delete": "Delete",
            "created_at": "Created At",
            "info": "Product Info",
            "seller_info_unavailable": "Seller information unavailable",
            "contact": "Contact Seller",
            "safe_transaction_message": "For safe transactions, please contact the seller through the platform message system",
            "contact_phone": "Contact Phone",
            "publish_success": "Product published successfully!",
            "publish_failed": "Failed to publish",
            "categories": {
                "electronics": "Electronics",
                "household": "Household Items",
                "clothing": "Clothing",
                "books": "Books",
                "sports": "Sports Equipment",
                "other": "Other"
            },
            "conditions": {
                "new": "New",
                "like_new": "Like New",
                "minor_wear": "Minor Wear",
                "normal": "Normal Use",
                "heavy_wear": "Heavy Use"
            },
            "image_not_found": "Image file not found"
        },
        "messages": {
            "messages_center": "Message Center",
            "no_conversations": "You have no conversations yet",
            "start_chat": "Start chatting with other users",
            "start_chat_prompt": "Start chatting with other users",
            "select_contact": "Please select a contact from the left side to start chatting",
            "select_contact_first": "Please select a contact first to start chatting",
            "start_conversation": "Start the conversation!",
            "type_message": "Type a message...",
            "input_label": "Message",
            "input_placeholder": "Type a message...",
            "send": "Send",
            "send_button": "Send",
            "send_success": "Message sent successfully",
            "send_error": "Failed to send message",
            "refresh_messages": "Refresh messages",
            "refresh": "Refresh messages",
            "refresh_help": "Refresh message list",
            "sending_message": "Sending message...",
            "message_sent_success": "Message sent successfully!",
            "message_sent_failed": "Failed to send message",
            "error_sending": "Error sending message: {}",
            "cannot_contact_self": "Cannot contact yourself",
            "chat_settings": "Chat Settings",
            "chat_settings_help": "Chat-related settings",
            "operation_irreversible": "Operation irreversible, please use with caution!",
            "clear_chat_history": "Clear Chat History",
            "clear_history_help": "Delete all chat records with this user (irreversible)",
            "confirm_clear_history": "Confirm clearing all chat history? This operation is irreversible!",
            "confirm": "Confirm Clear",
            "cancel": "Cancel"
        },
        "profile": {
            "username": "Username",
            "email": "Email",
            "login_required": "Please login first"
        },
        "general": {
            "save": "Save",
            "cancel": "Cancel",
            "confirm": "Confirm",
            "success": "Success",
            "error": "Error",
            "warning": "Warning",
            "info": "Info",
            "settings": "Settings",
            "price": "Price",
            "description": "Description",
            "category": "Category",
            "time": "Time",
            "date": "Date"
        }
    },
    # 日语
    "ja": {
        "app_title": "古物取引プラットフォーム",
        "page_titles": {
            "search": "商品検索",
            "auth": "ユーザー認証",
            "publish": "商品発表",
            "my_products": "マイ商品",
            "profile": "ユーザープロフィール",
            "messages": "メッセージセンター"
        },
        "menu": {
            "title": "ナビゲーションメニュー",
            "search": "🔍 商品検索",
            "messages": "💬 メッセージ",
            "publish": "➕ 商品を発行",
            "my_products": "📦 私の商品",
            "profile": "👤 プロフィール",
            "auth": "🔐 認証"
        },
        "auth": {
            "login": "ログイン",
            "register": "登録",
            "username": "ユーザー名",
            "email": "メール",
            "password": "パスワード",
            "confirm_password": "パスワード確認",
            "new_password": "新しいパスワード",
            "already_account": "アカウントをお持ちですか？",
            "no_account": "アカウントをお持ちでないですか？",
            "login_success": "ログイン成功！",
            "register_success": "登録成功！",
            "login_failed": "ログインに失敗しました。ユーザー名とパスワードを確認してください",
            "register_failed": "登録に失敗しました。入力情報を確認してください",
            "logout": "ログアウト",
            "login_prompt": "全機能を使用するにはログインしてください",
            "please_login": "まずログインしてください",
            "login_button": "ログイン",
            "register_button": "登録",
            "fill_all_fields": "すべてのフィールドを入力してください",
            "password_mismatch": "パスワードが一致しません",
            "enter_username_password": "ユーザー名とパスワードを入力してください",
            "username_email_exists": "ユーザー名またはメールアドレスは既に存在します",
            "reset_password": "パスワード再設定",
            "send_code": "認証コード送信",
            "verification_code": "認証コード",
            "reset_password_button": "パスワードをリセット",
            "email_not_configured": "メールサービスが未設定のため、コードを送信できません",
            "email_sent": "メールを送信しました。受信箱をご確認ください",
            "email_send_failed": "メール送信に失敗しました: {}",
            "user_not_found_by_email": "該当メールのユーザーが見つかりません",
            "code_invalid": "認証コードが無効です",
            "code_expired": "認証コードの有効期限が切れました。再送してください",
            "reset_success": "パスワードの再設定が完了しました。新しいパスワードでログインしてください"
        },
        "search": {
            "search_bar": "商品を検索...",
            "search_button": "検索",
            "cancel": "キャンセル",
            "filter_category": "カテゴリー",
            "sort_price": "価格で並び替え",
            "sort_newest": "新しい順",
            "sort_price_low": "価格: 安い順",
            "sort_price_high": "価格: 高い順",
            "all": "すべて",
            "price_range": "価格範囲",
            "price_low": "最低価格",
            "price_high": "最高価格",
            "no_results": "該当する商品がありません",
            "view_details": "詳細を見る",
            "results_found": "見つかりました",
            "products": "件の商品",
            "back_to_list": "リストに戻る"
        },
        "product": {
            "multilingual_description": "多言語説明",
            "optional_description": "任意",
            "at_least_one_description_required": "少なくとも1つの言語の説明を提供する必要があります",
            "publish_title": "新しい商品を発表",
            "product_name": "商品名",
            "product_description": "説明",
            "product_image": "商品画像",
            "product_price": "価格",
            "product_category": "カテゴリー",
            "product_image": "商品画像",
            "publish_button": "発表",
            "update_button": "更新",
            "delete_button": "削除",
            "confirm_delete": "この商品を削除してもよろしいですか？",
            "published_success": "商品が正常に発表されました！",
            "updated_success": "商品が正常に更新されました！",
            "deleted_success": "商品が正常に削除されました！",
            "seller": "販売者",
            "contact_seller": "販売者に連絡",
            "cannot_contact_self": "自分に連絡することはできません",
            "login_to_contact": "販売者に連絡するにはログインしてください",
            "title": "商品名",
            "description": "商品の説明",
            "price": "価格",
            "category": "カテゴリー",
            "condition": "状態",
            "contact_info": "連絡先",
            "upload_image": "画像をアップロード",
            "submit": "商品を発表",
            "fill_required": "すべての必須フィールドに入力してください",
            "no_products": "まだ商品を発表していません",
            "edit": "編集",
            "delete": "削除",
            "created_at": "作成日時",
            "info": "商品情報",
            "seller_info_unavailable": "販売者情報は利用できません",
            "contact": "販売者に連絡",
            "safe_transaction_message": "安全な取引のために、プラットフォームのメッセージシステムを通じて販売者に連絡してください",
            "contact_phone": "連絡先電話番号",
            "publish_success": "商品が正常に発表されました！",
            "publish_failed": "発表に失敗しました",
            "categories": {
                "electronics": "電子製品",
                "household": "家庭用品",
                "clothing": "衣類",
                "books": "本",
                "sports": "スポーツ用品",
                "other": "その他"
            },
            "conditions": {
                "new": "新品",
                "like_new": "新品同様",
                "minor_wear": "軽度の使用痕跡",
                "normal": "通常の使用状態",
                "heavy_wear": "激しい使用状態"
            },
            "image_not_found": "画像ファイルが見つかりません"
        },
        "messages": {
            "messages_center": "メッセージセンター",
            "no_conversations": "まだ会話はありません",
            "start_chat": "他のユーザーとチャットを始めましょう",
            "start_chat_prompt": "他のユーザーとチャットを始めましょう",
            "select_contact": "左側から連絡先を選択してチャットを開始してください",
            "select_contact_first": "チャットを開始するには先に連絡先を選択してください",
            "start_conversation": "会話を始めましょう！",
            "type_message": "メッセージを入力...",
            "input_label": "メッセージ",
            "input_placeholder": "メッセージを入力...",
            "send": "送信",
            "send_button": "送信",
            "send_success": "メッセージが正常に送信されました",
            "send_error": "メッセージの送信に失敗しました",
            "refresh_messages": "メッセージを更新",
            "refresh": "メッセージを更新",
            "refresh_help": "メッセージリストを更新",
            "sending_message": "メッセージを送信中...",
            "message_sent_success": "メッセージが正常に送信されました！",
            "message_sent_failed": "メッセージの送信に失敗しました",
            "error_sending": "メッセージ送信エラー: {}",
            "cannot_contact_self": "自分に連絡することはできません",
            "chat_settings": "チャット設定",
            "chat_settings_help": "チャット関連の設定",
            "operation_irreversible": "操作は元に戻せませんので、慎重にお使いください！",
            "clear_chat_history": "チャット履歴を消去",
            "clear_history_help": "このユーザーとのすべてのチャット記録を削除します（元に戻せません）",
            "confirm_clear_history": "すべてのチャット履歴を消去しますか？この操作は元に戻せません！",
            "confirm": "消去を確認",
            "cancel": "キャンセル"
        },
        "profile": {
            "username": "ユーザー名",
            "email": "メール",
            "login_required": "まずログインしてください"
        },
        "general": {
            "save": "保存",
            "cancel": "キャンセル",
            "confirm": "確認",
            "success": "成功",
            "error": "エラー",
            "warning": "警告",
            "info": "情報",
            "settings": "設定",
            "price": "価格",
            "description": "説明",
            "category": "カテゴリー",
            "time": "時間",
            "date": "日付"
        }
    },
    # 韩语
    "ko": {
        "app_title": "중고거래 플랫폼",
        "page_titles": {
            "search": "상품 검색",
            "auth": "사용자 인증",
            "publish": "상품 게시",
            "my_products": "내 상품",
            "profile": "사용자 프로필",
            "messages": "메시지 센터"
        },
        "menu": {
            "title": "네비게이션 메뉴",
            "search": "🔍 상품 검색",
            "messages": "💬 메시지",
            "publish": "➕ 상품 게시",
            "my_products": "📦 내 상품",
            "profile": "👤 프로필",
            "auth": "🔐 로그인"
        },
        "auth": {
            "login": "로그인",
            "register": "회원가입",
            "username": "사용자명",
            "email": "이메일",
            "password": "비밀번호",
            "confirm_password": "비밀번호 확인",
            "new_password": "새 비밀번호",
            "already_account": "계정이 이미 있으신가요?",
            "no_account": "계정이 없으신가요?",
            "login_success": "로그인 성공！",
            "register_success": "회원가입 성공！",
            "login_failed": "로그인 실패, 사용자 이름과 비밀번호를 확인하세요",
            "register_failed": "회원가입 실패, 입력 정보를 확인하세요",
            "logout": "로그아웃",
            "login_prompt": "전체 기능을 사용하려면 로그인하세요",
            "please_login": "먼저 로그인해 주세요",
            "login_button": "로그인",
            "register_button": "회원가입",
            "fill_all_fields": "모든 필드를 입력해 주세요",
            "password_mismatch": "비밀번호가 일치하지 않습니다",
            "enter_username_password": "사용자 이름과 비밀번호를 입력해 주세요",
            "username_email_exists": "사용자 이름 또는 이메일이 이미 존재합니다",
            "reset_password": "비밀번호 재설정",
            "send_code": "인증 코드 보내기",
            "verification_code": "인증 코드",
            "reset_password_button": "비밀번호 재설정",
            "email_not_configured": "이메일 서비스가 설정되지 않아 코드를 보낼 수 없습니다",
            "email_sent": "이메일이 전송되었습니다. 받은 편지를 확인하세요",
            "email_send_failed": "이메일 전송 실패: {}",
            "user_not_found_by_email": "해당 이메일의 사용자를 찾을 수 없습니다",
            "code_invalid": "인증 코드가 올바르지 않습니다",
            "code_expired": "인증 코드가 만료되었습니다. 다시 전송해 주세요",
            "reset_success": "비밀번호가 재설정되었습니다. 새로운 비밀번호로 로그인해 주세요"
        },
        "search": {
            "search_bar": "상품 검색...",
            "search_button": "검색",
            "cancel": "취소",
            "filter_category": "카테고리",
            "sort_price": "가격 정렬",
            "sort_newest": "최신순",
            "sort_price_low": "가격: 낮은 순",
            "sort_price_high": "가격: 높은 순",
            "all": "전체",
            "price_range": "가격 범위",
            "price_low": "최소 가격",
            "price_high": "최대 가격",
            "no_results": "해당하는 상품이 없습니다",
            "view_details": "자세히 보기",
            "results_found": "발견",
            "products": "개의 제품",
            "back_to_list": "목록으로 돌아가기"
        },
        "product": {
            "multilingual_description": "다국어 설명",
            "optional_description": "선택사항",
            "at_least_one_description_required": "적어도 한 가지 언어의 설명을 제공해야 합니다",
            "publish_title": "새 상품 게시",
            "product_name": "상품 이름",
            "product_description": "설명",
            "product_image": "상품 이미지",
            "product_price": "가격",
            "product_category": "카테고리",
            "product_image": "상품 이미지",
            "publish_button": "게시",
            "update_button": "업데이트",
            "delete_button": "삭제",
            "confirm_delete": "이 상품을 삭제하시겠습니까?",
            "published_success": "상품 게시 성공！",
            "updated_success": "상품 업데이트 성공！",
            "deleted_success": "상품 삭제 성공！",
            "seller": "판매자",
            "contact_seller": "판매자에게 문의",
            "cannot_contact_self": "자신에게 문의할 수 없습니다",
            "login_to_contact": "판매자에게 문의하려면 로그인해야 합니다",
            "title": "제품 제목",
            "description": "제품 설명",
            "price": "가격",
            "category": "카테고리",
            "condition": "상태",
            "contact_info": "연락처",
            "upload_image": "이미지 업로드",
            "submit": "제품 게시",
            "fill_required": "모든 필수 필드를 입력하세요",
            "no_products": "아직 제품을 게시하지 않았습니다",
            "edit": "편집",
            "delete": "삭제",
            "created_at": "작성일",
            "info": "제품 정보",
            "seller_info_unavailable": "판매자 정보를 사용할 수 없습니다",
            "contact": "판매자 연락",
            "safe_transaction_message": "안전한 거래를 위해 플랫폼 메시지 시스템을 통해 판매자에게 연락하세요",
            "contact_phone": "연락처 전화번호",
            "publish_success": "제품이 성공적으로 게시되었습니다!",
            "publish_failed": "게시에 실패했습니다",
            "categories": {
                "electronics": "전자제품",
                "household": "가정용품",
                "clothing": "의류",
                "books": "서적",
                "sports": "스포츠 용품",
                "other": "기타"
            },
            "conditions": {
                "new": "새 제품",
                "like_new": "새 것처럼",
                "minor_wear": "약간의 마모",
                "normal": "정상 사용",
                "heavy_wear": "심한 마모"
            },
            "image_not_found": "이미지 파일을 찾을 수 없습니다"
        },
        "messages": {
            "messages_center": "메시지 센터",
            "no_conversations": "아직 대화가 없습니다",
            "start_chat": "다른 사용자와 대화를 시작하세요",
            "start_chat_prompt": "다른 사용자와 대화를 시작하세요",
            "select_contact": "대화를 시작하려면 왼쪽에서 연락처를 선택하세요",
            "select_contact_first": "대화를 시작하려면 먼저 연락처를 선택하세요",
            "start_conversation": "대화를 시작하세요！",
            "type_message": "메시지를 입력하세요...",
            "input_label": "메시지",
            "input_placeholder": "메시지를 입력하세요...",
            "send": "전송",
            "send_button": "전송",
            "send_success": "메시지 전송 성공",
            "send_error": "메시지 전송 실패",
            "refresh_messages": "메시지 새로고침",
            "refresh": "메시지 새로고침",
            "refresh_help": "메시지 목록 새로고침",
            "sending_message": "메시지를 보내는 중...",
            "message_sent_success": "메시지 전송 성공！",
            "message_sent_failed": "메시지 전송 실패",
            "error_sending": "메시지 전송 오류: {}",
            "cannot_contact_self": "자신에게 문의할 수 없습니다",
            "chat_settings": "채팅 설정",
            "chat_settings_help": "채팅 관련 설정",
            "operation_irreversible": "작업은 되돌릴 수 없으니 주의하세요！",
            "clear_chat_history": "채팅 기록 지우기",
            "clear_history_help": "이 사용자와의 모든 채팅 기록을 삭제합니다（되돌릴 수 없음）",
            "confirm_clear_history": "모든 채팅 기록을 지울까요？이 작업은 되돌릴 수 없습니다！",
            "confirm": "확인 지우기",
            "cancel": "취소"
        },
        "profile": {
            "username": "사용자명",
            "email": "이메일",
            "login_required": "먼저 로그인하세요"
        },
        "general": {
            "save": "저장",
            "cancel": "취소",
            "confirm": "확인",
            "success": "성공",
            "error": "오류",
            "warning": "경고",
            "info": "정보",
            "settings": "설정",
            "price": "가격",
            "description": "설명",
            "category": "카테고리",
            "time": "시간",
            "date": "날짜"
        }
    }
}

# 获取当前语言
def get_current_language():
    if 'language' not in st.session_state:
        st.session_state.language = 'zh'  # 默认中文
    return st.session_state.language

# 设置语言
def set_language(lang):
    if lang in LANGUAGES:
        st.session_state.language = lang
        return True
    return False

# 获取翻译文本
def t(key, *args):
    lang = get_current_language()
    # 处理嵌套键，如 'auth.login'
    keys = key.split('.')
    value = TRANSLATIONS.get(lang, TRANSLATIONS['zh'])
    
    for k in keys:
        if isinstance(value, dict) and k in value:
            value = value[k]
        else:
            # 如果找不到翻译，返回原始键
            return key
    
    # 如果有参数，进行格式化
    if args:
        return value.format(*args)
    return value

# 获取语言选择器组件
def get_language_selector():
    col1, col2 = st.columns([1, 1])
    with col2:
        st.write(" ")
        selected_lang = st.selectbox(
            "Language",
            list(LANGUAGES.keys()),
            format_func=lambda x: LANGUAGES[x],
            index=list(LANGUAGES.keys()).index(get_current_language()),
            key="language_selector",
            label_visibility="visible"
        )
        if selected_lang != get_current_language():
            set_language(selected_lang)
            st.rerun()
